### ISSUE TITLE
Remove embeds from discord links

### ISSUE THREAD

**Issue by pl9ed** [josephmate/FreeGameNotifier#3]
![image](https://user-images.githubusercontent.com/9086453/177042243-08d78c77-4af0-4968-b3b7-26deff94ae65.png)

Bot embeds links by default and it floods the channel if embeds are enabled. We can wrap the link in `<>` to automatically prevent this.

```
FREE: Some Game at <link>
```

![image](https://user-images.githubusercontent.com/9086453/177042185-d175d7e0-bfc0-4b3a-9b06-928a4700482a.png)

**Comment by josephmate** [comment]
Resolved by https://github.com/josephmate/FreeGameNotifier/pull/4
